### ISSUE TITLE
GceMetadataQuery failures when upgrading to App Engine standard + Java 11 bundled services

### ISSUE THREAD

**Issue by ghost** [GoogleCloudPlatform/cloud-debug-java#18]
We are currently migrating our App Engine standard application from Java 8 to Java 11 using the bundled services (https://cloud.google.com/blog/products/serverless/support-for-app-engine-services-in-second-generation-runtimes).

We made it as far as that the application seems to be running as expected.
The following errors are showing up in our logs every 10 seconds, however:

`Failed to query GCE metadata service`

and then

```
java.io.IOException: com.google.apphosting.api.ApiProxy$CallNotFoundException: Can't make API call urlfetch.Fetch in a thread that is neither the original request thread nor a thread created by ThreadManager
at com.google.appengine.api.urlfetch.URLFetchServiceImpl.fetch(URLFetchServiceImpl.java:70)
at com.google.apphosting.utils.security.urlfetch.URLFetchServiceStreamHandler$Connection.fetchResponse(URLFetchServiceStreamHandler.java:609)
at com.google.apphosting.utils.security.urlfetch.URLFetchServiceStreamHandler$Connection.getInputStream(URLFetchServiceStreamHandler.java:488)
at com.google.devtools.cdbg.debuglets.java.GceMetadataQuery.readResponse(Unknown Source)
at com.google.devtools.cdbg.debuglets.java.GceMetadataQuery.queryMetadataAttribute(Unknown Source)
at com.google.devtools.cdbg.debuglets.java.GceMetadataQuery.getProjectId(Unknown Source)
at com.google.devtools.cdbg.debuglets.java.GcpHubClient.registerDebuggee(Unknown Source)
Caused by: com.google.apphosting.api.ApiProxy$CallNotFoundException: Can't make API call urlfetch.Fetch in a thread that is neither the original request thread nor a thread created by ThreadManager
at com.google.apphosting.api.ApiProxy$CallNotFoundException.foreignThread(ApiProxy.java:844)
at com.google.apphosting.api.ApiProxy.makeSyncCall(ApiProxy.java:117)
at com.google.appengine.api.urlfetch.URLFetchServiceImpl.fetch(URLFetchServiceImpl.java:54)
... 6 more

```

The App Engine standard Cloud Debugger setup for Java (https://cloud.google.com/debugger/docs/setup/java#gae-standard) says that no configuration is required.

So is this a bug or is there some configuration required after all?

**Comment by mctavish** [comment]
Thanks for the report.  This looks like a bug.  I will look into it.

**Comment by vpriesner** [comment]
@mctavish Any news on this? It's sadly keeping us from upgrading production to Java 11.

**Comment by mctavish** [comment]
This looks to be an incompatibility between the bundled services and the Cloud Debugger agent used with Java 11.  I've raised the issue within Google and it's being investigated.
